# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#

# from recommonmark.parser import CommonMarkParser
# source_parsers = {
#     '.md': CommonMarkParser,
# }
# source_suffix = ['.rst', '.md']

# 注意：如果你想要构建这篇文档你要使用make html
# 但是前提你需要有python3.5以上并且安装了sphinx和sphinx_rtd_theme模块
# pip install sphinx sphinx_rtd_theme

import os
import sys
import shutil
import configparser

# -- 拟造假环境 -----------------------------------------------------

sys.path.insert(0, os.path.abspath('../madtornado/'))

if not os.path.isdir("./ancient/view"):
    shutil.copytree("../madtornado/ancient/view", "./ancient/view")
shutil.copyfile("../madtornado/config/tornado.cfg", "./config/tornado.cfg")

t_conf = configparser.ConfigParser()
t_conf.read('./config/tornado.cfg', encoding="utf-8-sig")

# -- Project information -----------------------------------------------------

project = 'madtornado'
copyright = '2019, SystemLight'
author = 'SystemLight'

# The full version, including alpha/beta/rc tags
release = t_conf.get("tornado", "frame_version")

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.todo',
    'sphinx.ext.viewcode'
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

master_doc = 'index'
